### ISSUE TITLE
Default login/password?

### ISSUE THREAD

**Issue by AndriyKalashnykov** [jonlehtinen/pfadmin_pfengine_ubuntu#6]
https://localhost:9999/pingfederate

Administrator : 2Federate - does not work, error message : "INVALID USERNAME OR PASSWORD."

**Comment by AndriyKalashnykov** [comment]
URL takes me to the screen where i can successfully import license, but then there is nothing on a screen to define default user.
![pingfederatrere i2081253/43854731-c91ff378-9b11-11e8-8641-47b09355ce51.jpg)

**Comment by jonlehtinen** [comment]
This was caused by the jrlehtinen/pfadmin:911 images in dockerhub having a configuration built into them. I stripped them down and repushed, so they should be genericized to the point where they will launch and you can customize the dockerfiles and build what you need using the scripts and files as a template.
